# 项目相关配置(开发环境)
itsm:
  # 名称
  name: itsm
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/itsm/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 9080
  servlet:
    # 应用的访问路径
    context-path: /itsm
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  config: classpath:logback-boot.xml
  level: 
    org.mof.cc.itsm: debug
    org.springframework: warn


# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    include: dev-druid,dev-redis
    # active: dev-druid,dev-redis
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
        

# MyBatis-plus
mybatis-plus:
    # 搜索指定包别名
    type-aliases-package: org.mof.cc.itsm.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath:/mapper/*Mapper.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
  
# Elasticsearch
es:
  userName: elastic
  passwd: UhPkKXbAdL6wZA1Bdzju
  hosts: 127.0.0.1:9200


