#Redis配置（使用Lettuce客户端）
spring:
    redis:
        host: 172.17.0.1
        port: 16379
        #Redis服务器连接密码（默认为空)
        password:   
        #连接超时时间（毫秒）
        timeout: 30000
        #lettuce客户端，可换成Jedis客户端
        lettuce:
            pool:
                #连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                #连接池中的最大空闲连接
                max-idle: 8
                #连接池中的最小空闲连接
                min-idle: 0
